name: PortfolioReport
on:
  push:
      branches:
        - master
  #schedule:
  #  - cron: '0 21 * * 1-6'

jobs:
  reporting:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install libraries
        run: |
          install.packages("devtools")
          devtools::install_github("laresbernardo/lares")
        shell: Rscript {0}
        
      - name: Create and send report
        env:
          PORTFOLIO_XLXS: ${{ secrets.PORTFOLIO_XLXS }}
          MAILGUN_URL: ${{ secrets.MAILGUN_URL }}
          MAILGUN_TOKEN: ${{ secrets.MAILGUN_TOKEN }}
        run: |
          data <- lares::stocks_file(Sys.getenv("PORTFOLIO_XLXS"))
          rep  <- lares::stocks_obj(data)
          lares::stocks_report(rep, dir = tempdir())
          report <- paste0(tempdir(), "/stocksReport.html")
          lares::mailSend(attachment = report, 
            subject = paste("Portfolio Report:", Sys.Date()), 
            creds = list(
              url = Sys.getenv("MAILGUN_URL"), 
              api = Sys.getenv("MAILGUN_TOKEN")))
        shell: Rscript {0}
    