name: PortfolioReport
on:
  push:
      branches:
        - master
  #schedule:
  #  - cron: '0 21 * * 1-6'

jobs:
  reporting:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install libraries
        run: |
          install.packages("devtools")
          install.packages("quantmod")
          devtools::install_github("laresbernardo/lares")
        shell: Rscript {0}
        
      - name: Create report
        env:
          PORTFOLIO_XLXS: ${{ secrets.PORTFOLIO_XLXS }}
        run: |
          data <- lares::stocks_file(Sys.getenv("PORTFOLIO_XLXS"))
          rep  <- lares::stocks_obj(data)
          lares::stocks_report(rep, dir = tempdir())
        shell: Rscript {0}
        
    - name: Send report
        env:
          MAILGUN_URL: ${{ secrets.MAILGUN_URL }}
          MAILGUN_TOKEN: ${{ secrets.MAILGUN_TOKEN }}
        run: |
          report <- paste0(tempdir(), "/stocksReport.html")
          lares::mailSend(attachment = report, 
            subject = paste("Portfolio Report:", Sys.Date()), 
            creds = list(
              url = Sys.getenv("MAILGUN_URL"), 
              api = Sys.getenv("MAILGUN_TOKEN")))
        shell: Rscript {0}
    